### ISSUE TITLE
Amoled theme

### ISSUE THREAD

**Issue by ImUbedk** [deckerst/aves#157] opened 2022-01-11 09:00 UTC
Everything is great just add a black theme

**Comment by deckerst** [comment] 2022-01-11 09:05
Isn't "Amoled theme" the same thing as "True dark theme (black)"?
If so, I'll close this one as a duplicate of #93 and you can upvote that issue with a thumbup reaction.

**Comment by Donkey-Doug** [comment] 2022-01-11 16:13
It is the same.

**Closed** 2022-01-11 23:33 UTC
Labels: close:duplicate, type:feature
