### ISSUE TITLE
Random crash when moving away from map with Google Maps layer

### ISSUE THREAD

**Issue by kha84** [deckerst/aves#333] opened 2022-09-15 11:03 UTC
**Describe the bug**
I tried to set the location for a photo, but app crashed - it exited to android UI. When I tried to switch back to it with using android taskbar, it cold started.

**To Reproduce**
The issue is not reproduced at will, but this is what I was doing:
1. Opened a photo without GPS coordinates to a fullscreen view
2. Swiping it up
3. Opening a [...] menu to edit location
4. Clicked on map, selected location, confirmed it - then app exited

[aves-logs-20220915_204507.txt](https://github.com/deckerst/aves/files/9574570/aves-logs-20220915_204507.txt)

**Comment by kha84** [comment] 2022-09-15 11:54
I also noticed, if I open a full map (by clicking on a map icon from a photo which is having GPS coordinates) many times for different photos, at some point phone becomes very unresponsive, like Aves is somehow memory leaking (Map widgets are created but not destroyed?). 

I wonder if they're tools like top/htop/btop exist for Android so I could confirm this :)

**Comment by kha84** [comment] 2022-09-15 13:44
I think I nailed it down and can reproduce at will. Here's what you need to do:
- open any photo, which has a GPS, to be shown at fullscreen (basically tap on it in a collection)
- swipe it up, and wait till minimap will appear
- swipe it down to return back to the mode when just photo is displayed fullscreen
- keep swiping up and down, and after few more turns you'll see the app crashes

**Comment by deckerst** [comment] 2022-09-15 14:20
Thanks for the report. Alas, it's a good news / bad news situation.

The good news is that you stumbled upon a known issue that has already been reported to Google by many people: https://github.com/flutter/flutter/issues/105965

The bad news is that Google hasn't fixed it yet, and there's nothing Aves can do to fix it on the app side.

Also, I tried many times to follow the steps you mentioned, but I can't reproduce the crash on my device. It's strange because my device is the same as yours (S10e with Android 12).

**Comment by kha84** [comment] 2022-09-15 15:44
It's actually good news, because when I switch to OpenStreetMap - I don't have this bug :) 

Yeah, it's kind of hard to reproduce it on purpose. I can provide a video on how to do that. I realized it's all about timings: if you're lucky enough to swipe down at the moment when map is about to be shown, app crashes.

**Comment by kha84** [comment] 2023-02-24 20:44
Hello there! I've seen you added a label "works for me". Does it mean something has changed (like framework was updated) and I can update & retest it?

**Comment by deckerst** [comment] 2023-02-24 21:41
No, i believe it's still not fixed, so some people may experience this. I've just not personally experienced it so far.

**Comment by deckerst** [comment] 2023-03-03 17:38
@kha84 actually, I haven't seen error reports for this issue in a long while, so I guess it's fixed in practice, even if the Flutter issue mentioned above isn't marked as fixed. I'll close this issue, but feel free to comment/reopen if you experience it again.

**Closed by deckerst** 2023-03-03 17:38 UTC
Labels: type:bug, bug:works-for-me, P2, bug:waiting-for-google
