### ISSUE TITLE
Support of Jpeg XL format

### ISSUE THREAD

**Issue by mahikeulbody** [deckerst/aves#530] opened 2023-02-17 16:54 UTC
Please support Jpeg XL format (such as [jxlviewer](https://github.com/oupson/jxlviewer) which uses libjxl library).

**Comment by gianni-rosato** [comment] 2023-02-17 19:43
Now that FFmpeg supports JPEG XL, & Aves uses ffmpeg for videos, I don't see a downside with implementing JXL support now.

**Comment by deckerst** [comment] 2023-02-17 21:30
Aves uses ffmpeg, true, but through fijkplayer so I can't choose the version of ffmpeg. Fijkplayer uses an old version of ffmpeg and it doesn't look like it's going to change any time soon.

**Comment by deckerst** [comment] 2023-02-17 21:32
Duplicate of #56.

**Closed by deckerst** 2023-02-17 21:32 UTC
Labels: type:feature
