### ISSUE TITLE
Remove tags

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#87] opened 2021-10-01 21:54 UTC
Make it possible to remove a tag from an image by long pressing it. Currently only hide and show in tags are possible:

![Screenshot_20211001-235331_Aves](https://user-images.githubusercontent.com/50382414/135690239-8afd2b2c-c3eb-4c2e-8e68-fdb1ae9ecd2e.png)

**Comment by deckerst** [comment] 2021-10-02 01:04
Duplicate of #1

**Closed** 2021-10-02 01:04 UTC
Labels: close:duplicate
