### ISSUE TITLE
duplicate images in newly added items

### ISSUE THREAD

**Issue by basings** [deckerst/aves#293] opened 2022-08-01 19:40 UTC
**Describe the bug**
Since 1.6.11 aves shows each image of the most recent day two times. It could also be the case for the last two days but so far I can't find a consistent pattern.

**System information and logs:**
````
Aves version: 1.6.11-izzy (Build 1077)
Flutter version: 3.3.0-0.0.pre (Channel beta)
Android version: 12 (SDK 32)
Android build: SQ3A.220705.003.A1.2022073100
Device: Google Pixel 6
Mobile services: ready
System locales: en_US
Aves locale: system -> en
Installer: com.machiav3lli.fdroid
````
Log
````
--------- beginning of main
08-01 21:33:59.884 29369 29369 I d.t.a.MainActivity: onCreate intent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=deckers.thibault.aves/.MainActivity bnds=[340,900][540,1100] }
08-01 21:33:59.976 29369 29369 I d.t.a.MainActivity: onStart
08-01 21:34:00.146 29369  3564 I flutter : Device has Google Play Services=true
08-01 21:34:00.149 29369  3564 I flutter : [sil] 2022-08-01 21:34:00.149448 [fijk] set log level FijkLogLevel{level:500, name:war}
08-01 21:34:00.150 29369  3564 I flutter : Report set keys build_mode=release, has_mobile_services=true, locales=en_US, time_zone=CEST (2:00:00.000000)
08-01 21:34:00.150 29369  3564 I flutter : App setup in 141ms
08-01 21:34:00.151 29369  3564 I flutter : [sil] 2022-08-01 21:34:00.151892 [fijk] native log level 500
08-01 21:34:00.153 29369  3564 I flutter : Apply display refresh rate: highest
08-01 21:34:00.209 29369  3564 I flutter : Access installed app inventory
08-01 21:34:00.209 29369  3564 I flutter : Report set key app_mode=AppMode.main
08-01 21:34:00.209 29369  3564 I flutter : Storage check complete in 47ms
08-01 21:34:00.286 29369  3564 I flutter : MediaStoreSource load essentials complete in 76ms
08-01 21:34:00.286 29369  3564 I flutter : MediaStoreSource refresh start
08-01 21:34:00.287 29369  3564 I flutter : MediaStoreSource refresh 0:00:00.000122 load 36 top entries
08-01 21:34:00.288 29369  3564 I flutter : Report log with message=Nav didPush to /collection
08-01 21:34:00.288 29369  3564 I flutter : Report log with message=Nav didRemove to unnamed null
08-01 21:34:00.295 29369  3564 I flutter : MediaStoreSource refresh 0:00:00.008718 fetch known entries
08-01 21:34:00.481 29369  3564 I flutter : MediaStoreSource refresh 0:00:00.194045 check obsolete entries
08-01 21:34:00.876 29369  3564 I flutter : MediaStoreSource refresh 0:00:00.589084 add known entries
08-01 21:34:00.923 29369  3564 I flutter : MediaStoreSource refresh 0:00:00.636060 load metadata
08-01 21:34:01.000 29369  3564 I flutter : Evict cached images for uri=content://media/external/images/media/4195, mimeType=image/jpeg, dateModifiedSecs=1623002663, rotationDegrees=0, isFlipped=false
08-01 21:34:01.000 29369  3564 I flutter : Evict cached images for uri=content://media/external/images/media/4682, mimeType=image/jpeg, dateModifiedSecs=1624802403, rotationDegrees=0, isFlipped=false
08-01 21:34:01.000 29369  3564 I flutter : Evict cached images for uri=content://media/external/images/media/5049, mimeType=image/jpeg, dateModifiedSecs=1631407320, rotationDegrees=0, isFlipped=false
08-01 21:34:01.000 29369  3564 I flutter : Evict cached images for uri=content://media/external/images/media/7333, mimeType=image/jpeg, dateModifiedSecs=1626939651, rotationDegrees=0, isFlipped=false
08-01 21:34:01.000 29369  3564 I flutter : Evict cached images for uri=content://media/external/images/media/7156, mimeType=image/jpeg, dateModifiedSecs=1622313650, rotationDegrees=0, isFlipped=false
08-01 21:34:01.000 29369  3564 I flutter : Evict cached images for uri=content://media/external/images/media/8825, mimeType=image/jpeg, dateModifiedSecs=1621400992, rotationDegrees=0, isFlipped=false
08-01 21:34:01.000 29369  3564 I flutter : Evict cached images for uri=content://media/external/images/media/6694, mimeType=image/jpeg, dateModifiedSecs=1621162574, rotationDegrees=0, isFlipped=false
08-01 21:34:01.001 29369  3564 I flutter : Evict cached images for uri=content://media/external/images/media/12305, mimeType=image/jpeg, dateModifiedSecs=1635268959, rotationDegrees=0, isFlipped=false
08-01 21:34:01.001 29369  3564 I flutter : Evict cached images for uri=content://media/external/images/media/10850, mimeType=image/jpeg, dateModifiedSecs=1617827501, rotationDegrees=0, isFlipped=false
08-01 21:34:01.001 29369  3564 I flutter : Evict cached images for uri=content://media/external/images/media/13633, mimeType=image/jpeg, dateModifiedSecs=1615968248, rotationDegrees=0, isFlipped=false
08-01 21:34:01.110 29369  3564 I flutter : MediaStoreSource refresh 0:00:00.823122 check obsolete paths
08-01 21:34:01.245 29369  3564 I flutter : MediaStoreSource refresh 0:00:00.958519 fetch new entries
08-01 21:34:01.337 29369  3564 I flutter : MediaStoreSource refresh 0:00:01.050572 analyze
08-01 21:34:01.341 29369  3564 I flutter : Device is connected=true
08-01 21:34:01.348 29369 29369 I d.t.a.AnalysisService: Create analysis service
08-01 21:34:01.369 29369 29369 I t.b     : Analysis service connected
08-01 21:34:01.369 29369  3564 I flutter : MediaStoreSource refresh 0:00:01.082852 done for 7710 known, 0 new, 0 removed
08-01 21:34:01.384 29369  3573 I flutter : Device has Google Play Services=true
08-01 21:34:01.386 29369  3573 I flutter : [sil] 2022-08-01 21:34:01.386247 [fijk] set log level FijkLogLevel{level:500, name:war}
08-01 21:34:01.386 29369  3573 I flutter : Analyzer create
08-01 21:34:01.386 29369 29369 D d.t.a.AnalysisService: background channel is ready
08-01 21:34:01.386 29369  3573 I flutter : Analyzer start for all entries
08-01 21:34:01.386 29369  3573 I flutter : [sil] 2022-08-01 21:34:01.386801 [fijk] native log level 500
08-01 21:34:01.407 29369  3573 I flutter : MediaStoreSource load essentials complete in 20ms
08-01 21:34:01.407 29369  3573 I flutter : MediaStoreSource refresh start
08-01 21:34:01.407 29369  3573 I flutter : MediaStoreSource refresh 0:00:00.000005 fetch known entries
08-01 21:34:01.525 29369  3573 I flutter : MediaStoreSource refresh 0:00:00.118020 check obsolete entries
08-01 21:34:01.585 29369  3573 I flutter : MediaStoreSource refresh 0:00:00.177223 add known entries
08-01 21:34:01.623 29369  3573 I flutter : MediaStoreSource refresh 0:00:00.215494 load metadata
08-01 21:34:01.683 29369  3573 I flutter : Evict cached images for uri=content://media/external/images/media/4195, mimeType=image/jpeg, dateModifiedSecs=1623002663, rotationDegrees=0, isFlipped=false
08-01 21:34:01.683 29369  3573 I flutter : Evict cached images for uri=content://media/external/images/media/4682, mimeType=image/jpeg, dateModifiedSecs=1624802403, rotationDegrees=0, isFlipped=false
08-01 21:34:01.683 29369  3573 I flutter : Evict cached images for uri=content://media/external/images/media/5049, mimeType=image/jpeg, dateModifiedSecs=1631407320, rotationDegrees=0, isFlipped=false
08-01 21:34:01.684 29369  3573 I flutter : Evict cached images for uri=content://media/external/images/media/7333, mimeType=image/jpeg, dateModifiedSecs=1626939651, rotationDegrees=0, isFlipped=false
08-01 21:34:01.684 29369  3573 I flutter : Evict cached images for uri=content://media/external/images/media/7156, mimeType=image/jpeg, dateModifiedSecs=1622313650, rotationDegrees=0, isFlipped=false
08-01 21:34:01.684 29369  3573 I flutter : Evict cached images for uri=content://media/external/images/media/8825, mimeType=image/jpeg, dateModifiedSecs=1621400992, rotationDegrees=0, isFlipped=false
08-01 21:34:01.684 29369  3573 I flutter : Evict cached images for uri=content://media/external/images/media/6694, mimeType=image/jpeg, dateModifiedSecs=1621162574, rotationDegrees=0, isFlipped=false
08-01 21:34:01.684 29369  3573 I flutter : Evict cached images for uri=content://media/external/images/media/12305, mimeType=image/jpeg, dateModifiedSecs=1635268959, rotationDegrees=0, isFlipped=false
08-01 21:34:01.685 29369  3573 I flutter : Evict cached images for uri=content://media/external/images/media/10850, mimeType=image/jpeg, dateModifiedSecs=1617827501, rotationDegrees=0, isFlipped=false
08-01 21:34:01.685 29369  3573 I flutter : Evict cached images for uri=content://media/external/images/media/13633, mimeType=image/jpeg, dateModifiedSecs=1615968248, rotationDegrees=0, isFlipped=false
08-01 21:34:01.760 29369  3573 I flutter : MediaStoreSource refresh 0:00:00.352329 check obsolete paths
08-01 21:34:01.876 29369  3573 I flutter : MediaStoreSource refresh 0:00:00.468781 fetch new entries
08-01 21:34:01.981 29369  3573 I flutter : MediaStoreSource refresh 0:00:00.573335 analyze
08-01 21:34:02.227 29369  3573 I flutter : Device is connected=true
08-01 21:34:02.938 29369  3573 I flutter : MediaStoreSource refresh 0:00:01.531022 done for 7710 known, 0 new, 0 removed
08-01 21:34:02.939 29369  3564 I flutter : Analysis completed
08-01 21:34:02.944 29369 29369 I d.t.a.AnalysisService: Destroy analysis service
08-01 21:34:17.457 29369  3564 I flutter : _AvesAppState lifecycle inactive
08-01 21:34:17.498 29369  3564 I flutter : Saved 36 top entries in 40ms
08-01 21:34:18.142 29369 29369 I d.t.a.MainActivity: onStop
08-01 21:34:18.143 29369  3564 I flutter : _AvesAppState lifecycle paused
08-01 21:34:32.467 29369 29369 I d.t.a.MainActivity: onStart
08-01 21:34:32.474 29369  3564 I flutter : _AvesAppState lifecycle resumed
08-01 21:34:32.538 29369  3586 I OpenGLRenderer: Davey! duration=32345ms; Flags=1, FrameTimelineVsyncId=1557780, IntendedVsync=37057116491753, Vsync=37057116491753, InputEventId=0, HandleInputStart=37057116735785, AnimationStart=37057116737332, PerformTraversalsStart=37057117027574, DrawStart=37057120574286, FrameDeadline=37057133091753, FrameInterval=37057116730740, FrameStartTime=16666667, SyncQueued=37057122571194, SyncStart=37057122627428, IssueDrawCommandsStart=37057123462755, SwapBuffers=37057130139675, FrameCompleted=37089461970583, DequeueBufferDuration=802002, QueueBufferDuration=636067, GpuCompleted=37089461970583, SwapBuffersCompleted=37057130809679, DisplayPresentTime=-2121335188909661553, 
08-01 21:34:34.097 29369  3564 I flutter : Report log with message=Nav didPush to unnamed _PopupMenuRoute<EntrySetAction?>
08-01 21:34:35.197 29369  3564 I flutter : Report log with message=Nav didPop to /collection
08-01 21:34:37.019 29369  3564 I flutter : Report log with message=Nav didPush to /about
08-01 21:34:40.499 29369  3564 I flutter : _AvesAppState lifecycle inactive
08-01 21:34:40.550 29369 29369 I d.t.a.MainActivity: onStop
08-01 21:34:40.622 29369  3564 I flutter : Saved 36 top entries in 122ms
08-01 21:34:40.623 29369  3564 I flutter : _AvesAppState lifecycle paused
08-01 21:35:12.522 29369 29369 I d.t.a.MainActivity: onStart
08-01 21:35:12.532 29369  3564 I flutter : _AvesAppState lifecycle resumed
08-01 21:35:12.581 29369 30290 I OpenGLRenderer: Davey! duration=72401ms; Flags=1, FrameTimelineVsyncId=1557780, IntendedVsync=37057116491753, Vsync=37057116491753, InputEventId=0, HandleInputStart=37057116735785, AnimationStart=37057116737332, PerformTraversalsStart=37057117027574, DrawStart=37057120574286, FrameDeadline=37057149758420, FrameInterval=37057116730740, FrameStartTime=16666667, SyncQueued=37057122571194, SyncStart=37057122627428, IssueDrawCommandsStart=37057123462755, SwapBuffers=37057130139675, FrameCompleted=37129518370057, DequeueBufferDuration=802002, QueueBufferDuration=636067, GpuCompleted=37129518370057, SwapBuffersCompleted=37057130809679, DisplayPresentTime=-2121335188909661553, 
08-01 21:35:15.031 29369  3564 I flutter : _AvesAppState lifecycle inactive
08-01 21:35:15.089 29369  3564 I flutter : Saved 36 top entries in 58ms
08-01 21:35:15.091 29369 29369 I d.t.a.MainActivity: onStop
08-01 21:35:15.092 29369  3564 I flutter : _AvesAppState lifecycle paused
08-01 21:36:05.135 29369 29369 I d.t.a.MainActivity: onStart
08-01 21:36:05.159 29369  3564 I flutter : _AvesAppState lifecycle resumed
08-01 21:36:05.208 29369  3586 I OpenGLRenderer: Davey! duration=125019ms; Flags=1, FrameTimelineVsyncId=1557780, IntendedVsync=37057116491753, Vsync=37057116491753, InputEventId=0, HandleInputStart=37057116735785, AnimationStart=37057116737332, PerformTraversalsStart=37057117027574, DrawStart=37057120574286, FrameDeadline=37057166425087, FrameInterval=37057116730740, FrameStartTime=16666667, SyncQueued=37057122571194, SyncStart=37057122627428, IssueDrawCommandsStart=37057123462755, SwapBuffers=37057130139675, FrameCompleted=37182136104255, DequeueBufferDuration=802002, QueueBufferDuration=636067, GpuCompleted=37182136104255, SwapBuffersCompleted=37057130809679, DisplayPresentTime=-2121335188909661553, 
08-01 21:36:06.583 29369  3564 I flutter : Report log with message=Nav didPop to /collection
08-01 21:36:31.088 29369  3564 I flutter : _AvesAppState lifecycle inactive
08-01 21:36:31.129 29369  3564 I flutter : Saved 36 top entries in 40ms
08-01 21:36:31.133 29369 29369 I d.t.a.MainActivity: onStop
08-01 21:36:31.133 29369  3564 I flutter : _AvesAppState lifecycle paused
08-01 21:37:29.121 29369 29369 I d.t.a.MainActivity: onStart
08-01 21:37:29.140 29369  3564 I flutter : _AvesAppState lifecycle resumed
08-01 21:37:29.186 29369 30290 I OpenGLRenderer: Davey! duration=176688ms; Flags=1, FrameTimelineVsyncId=1559798, IntendedVsync=37089427479969, Vsync=37089427479969, InputEventId=2053655941, HandleInputStart=37089428585817, AnimationStart=37089428586631, PerformTraversalsStart=37089428587079, DrawStart=37089455427574, FrameDeadline=37089460746636, FrameInterval=37089428582969, FrameStartTime=16666667, SyncQueued=37089456106651, SyncStart=37089456128379, IssueDrawCommandsStart=37089456286094, SwapBuffers=37089461989504, FrameCompleted=37266116304939, DequeueBufferDuration=1219238, QueueBufferDuration=908691, GpuCompleted=37266116304939, SwapBuffersCompleted=37089462969525, DisplayPresentTime=-8178287817334288512, 
08-01 21:37:31.461 29369  3564 I flutter : Report log with message=Nav didPush to /about
08-01 21:37:43.651 29369  3564 I flutter : _AvesAppState lifecycle inactive
08-01 21:37:43.698 29369 29369 I d.t.a.MainActivity: onStop
08-01 21:37:43.774 29369  3564 I flutter : Saved 36 top entries in 123ms
08-01 21:37:43.775 29369  3564 I flutter : _AvesAppState lifecycle paused
08-01 21:37:52.202 29369 29369 I d.t.a.MainActivity: onStart
08-01 21:37:52.212 29369  3564 I flutter : _AvesAppState lifecycle resumed
08-01 21:37:52.255 29369 31839 I OpenGLRenderer: Davey! duration=159696ms; Flags=1, FrameTimelineVsyncId=1562822, IntendedVsync=37129491949943, Vsync=37129491949943, InputEventId=1172821643, HandleInputStart=37129492213319, AnimationStart=37129492214621, PerformTraversalsStart=37129492215435, DrawStart=37129510935975, FrameDeadline=37129525216610, FrameInterval=37129492209494, FrameStartTime=16666667, SyncQueued=37129512638327, SyncStart=37129512692486, IssueDrawCommandsStart=37129512943584, SwapBuffers=37129518565044, FrameCompleted=37289188650816, DequeueBufferDuration=1799927, QueueBufferDuration=1302246, GpuCompleted=37289188650816, SwapBuffersCompleted=37129519911643, DisplayPresentTime=31244173394051169, 
````

**Comment by deckerst** [comment] 2022-08-01 20:47
Thanks for the report.

I'm not sure i understand the issue. If you take a screenshot or take a picture with your camera now, you see the new image twice in Aves, and they both refer to the same file on storage? Is it consistent and reproducible with any new image?

**Comment by basings** [comment] 2022-08-02 09:10
Sorry for being not precise enough.

Following image shows my aves gallery from Sunday. 

![screenshsot](https://user-images.githubusercontent.com/92867705/182335539-2a1eba66-4e53-47f5-8e88-d32024a75052.jpg)

The pictures I took today and yesterday are shown normally. The pictures from Sunday are all duplicates. If I delete one, the other one gets removed after a millisecond as well. They both point to the same file on storage. 

So far I could not determine a reproducible pattern. I observed it now since the update but can't find anything. I think today's images are never shown twice.

- 2022-08-01: single
- 2022-07-31: single
- 2022-07-30: -
- 2022-07-29: four videos 3 times, another one 4 times, another one 2 times. 1 motion photo 3 times. other photos 2 times and 2 photos one time.
- 2022-07-28: - 2 videos 4 times. 1 photo 3 times. 7 photos 1 time.
- 2022-07-27: -
- 2022-07-26: and all before are shown normally. google photos shows all images normally.

**Comment by basings** [comment] 2022-08-02 09:11
This didn't happen in versions below 1.6.11

**Comment by basings** [comment] 2022-08-02 09:22
Probably I should've done it earlier but I didn't think of it. I just cleared storage and reopened aves. Now it's back to normal. Closing the case?

**Comment by deckerst** [comment] 2022-08-02 09:46
Thanks for the details. I'll keep this issue open. I can't reproduce it, but I should take a look to strengthen the code against this situation.

In the meantime, if it happens again, instead of resetting everything, you could move the duplicated items to another album and this should keep only one item per file.

**Comment by basings** [comment] 2022-08-02 11:26
Guess who's back.

I downloaded an image an hour ago and it appears three times in aves. It's an avif file, until I cleared the storage, I couldn't display avif in aves (reaaally happy that it's possible now!). I downloaded another avif photo and it only appears one time.

I moved one displayed file to another folder and immediately it was shown only once.

**Comment by petazonk** [comment] 2022-08-29 05:45
I have the same problem in that I get duplicate thumbnails pointing to the same image (same thing as the screenshot above). This started for me around early August when I was on Android 12 and the current version of Aves. The problem still exists on Android 13 on my Pixel 6 Pro. It doesn't always happen and I haven't worked out what is causing it. When I used F-Stop or Google Photos I can see that the photos are not duplicated. Rescanning the folder doesn't fix the problem.

**Comment by deckerst** [comment] 2022-08-29 12:29
Thanks for the feedback. It randomly happened to me once too, so i understand the symptoms. I tried to reproduce the issue in various ways, to no avail. From my understanding, if Aves gets corrupted like this, the only way to fix it is if the app "rediscovers" the items, so either 1) moving the items to another directory and reopening the app, or 2) wiping the app data and starting from scratch. Needless to say, this is unacceptable and i consider this a serious issue (hence the `P3` label). I intend to release a new version as soon as i find and validate a fix.

**Comment by deckerst** [comment] 2022-08-29 21:53
@basings @petazonk I just released Aves v1.6.13. It includes a fix that prevents duplicate items in a specific situation. I can't be sure it's the same situation in your case, but it's highly probable.

The fix will prevent new duplicates, but it won't clean up existing duplicates.

I'll close this issue for now, but feel free to comment if you experience the issue again with the latest version.

**Closed by deckerst** 2022-08-29 21:53 UTC
Labels: type:bug, bug:worksforme, collection model, P3

**Comment by deckerst** [comment] 2022-10-24 17:19
@basings @petazonk since the issue got supposedly fixed, did you find any new duplicate items?

I'm asking because I recently got some similar reports (cf #368), but it's unclear yet whether the duplicates in these reports appeared with the latest version of Aves or an older one.

**Comment by basings** [comment] 2022-10-25 06:51
No duplicates here either. Thanks!
