### ISSUE TITLE
Editing some WebP corrupts the file

### ISSUE THREAD

**Issue by anaskaejdar** [deckerst/aves#721] opened 2023-08-21 17:59 UTC
**Describe the bug**
If you use Aves to move a WebP image to a different folder/album, then the file is corrupted. Once that happens, Aves can't open it, and neither can any other image viewer.

**To Reproduce**
1. Download a WebP from facebook or wherever
2. In Aves, move it from “Downloads” to a different album, ie: “Memes.”
3. Hmmm... Image has no preview thembnail anymore. Try opening it.
4. Image doesn't load.

**Expected behavior**
The image should simply be moved to a different folder.

**Screenshots**
![Screenshot_۲۰۲۳۰۸۲۱_۱۰۵۲۱۰_Aves](https://github.com/deckerst/aves/assets/32847759/037e027b-2896-4d3d-900f-a7c4c95f53c2)
![Screenshot_۲۰۲۳۰۸۲۱_۱۰۵۳۲۳_Aves](https://github.com/deckerst/aves/assets/32847759/c693bc5e-3874-4bbb-84ff-50f62ffd4e5a)

**System information and logs:**
Package: deckers.thibault.aves
Installer: com.machiav3lli.fdroid
Aves version: 1.8.9-izzy, build 10001
Flutter: stable 3.10.3
Android version: 13, API 33
Android build: TP1A.220624.014.S908USQS3CWF2
Device: samsung SM-S908U
Geocoder: ready
Mobile services: ready
System locales: fa_IR, tg_Cyrl_TJ
Storage volumes: /storage/emulated/0/
Storage grants:
/storage/emulated/0/Pictures/,  /storage/emulated/0/Documents/, /storage/emulated/0/Music/, /storage/emulated/0/DCIM/
Error reporting: false
Logs don't contain the event at this time. Next time it happens, I can give you logs.

**Additional context**

**Comment by deckerst** [comment] 2023-08-21 18:02
For you, it happens every time, right?

Can you try with the latest release v1.9.0 (just out yesterday, maybe not on the stores yet but you can already get it from the GitHub releases)?

**Comment by deckerst** [comment] 2023-08-21 18:10
Thanks for following up.

I can't reproduce the issue on my device with the webp files I have. Could you provide a sample that create the issue for you? And logs would really help.

**Comment by anaskaejdar** [comment] 2023-08-21 18:16
Here's a sample. I tried copy instead of move, and actually both files were corrupted. Maybe that helps figure out at which stage the problem happens.

![img_2_1692641733473](https://github.com/deckerst/aves/assets/32847759/cc59a49d-6b0a-4872-a1ca-40f2bcba5864)

**Comment by deckerst** [comment] 2023-08-21 18:21
I don't know why it would happen, but I guess the step when it gets corrupted is when saving the metadata date before moving/copying an undated item. I guess you enabled this and checked `do not ask again`, so you don't see the prompt anymore.

With that in mind, I tried moving undated webp items on my device, and it edits it and moves it without an issue, so there must be something else messing with the webp edition.

Instead of moving it, does it get corrupted if you simply edit it (by 1. rotating it, 2. editing its location, or 3. editing its date)?

One thing I need to try is set my device in farsi, as it can have an impact on how numbers are represented in code!

**Comment by anaskaejdar** [comment] 2023-08-21 18:59
>Instead of moving it, does it get corrupted if you simply edit it (by 1. rotating it, 2. editing its location, or 3. editing its date)?

4, all of the above.

Good call on the dates thing, by the way. I wiped the app data and tried again, but without saving the date. It moves without issue as long as the date isn't saved.

**Comment by deckerst** [comment] 2023-08-21 19:02
I've managed to reproduce the issue with your sample. Basically any editing will wreck the file, as you have confirmed.

The strange thing is that all my other webp files do not have the issue, and I can't pinpoint yet what's special about your sample.

**Comment by deckerst** [comment] 2023-08-21 19:03
> I wiped the app data

Too late for this time, but next time you can go to `Settings` > `Navigation` > `Confirmation dialogs` and re-enable those you need.

**Comment by deckerst** [comment] 2023-08-21 22:41
The library I'm using for editing metadata seems to mishandle some WEBP, but I don't know why and what kind of WEBP are affected. I "fixed" this by making Aves fail when detecting corruption.

**Closed by deckerst** 2023-08-21 22:41 UTC
Labels: type:bug, bug:reproduced, P0
