### ISSUE TITLE
Option in settings to enable/disable video playback in thumbnail

### ISSUE THREAD

**Issue by Ingegneus** [deckerst/aves#161] opened 2022-01-18 21:29 UTC
**Is your feature request related to a problem? Please describe.**
it's not a problem but something that makes the user experience more seamless i believe.

**Describe the solution you'd like**
pretty much what the title says. an option to enable/disable video playback when the videos are shown as thumbnails.

**Describe alternatives you've considered**

**Additional context**

**Comment by deckerst** [comment] 2022-01-18 23:42
Duplicate of #20. You can upvote that issue with a thumb-up reaction 👍.

**Closed by deckerst** 2022-01-18 23:42 UTC
Labels: close:duplicate, type:feature
