### ISSUE TITLE
New feature: Machine learning-powered tagging assistant

### ISSUE THREAD

**Issue by DodoLeDev** [deckerst/aves#674] opened 2023-06-29 14:47 UTC
**Is your feature request related to a problem? Please describe.**
Basically, Aves was designed to be a media tagger application. However, tagging has to be done manually for each picture.

**Describe the solution you'd like**
Because as we tag our photos, a coherence can be easily found (e.g. 98% of my 'meme'-tagged pictures have +50% of white zones), why not provide a tool which suggests which tags we could add to pictures?

**Describe alternatives you've considered**
For now, I'm batch-tagging images based on folder.

**Additional context**
I've done some research about which libraries you can use in order to achieve this, and the best I have found is: [Google's ML Kit](https://developers.google.com/ml-kit/vision/image-labeling)

**_Oh no! Google will have access to all my pictures!_**
That's also the first thing I said to myself, and fortunately, this tool is also available totally offline, [by using custom models](https://developers.google.com/ml-kit/vision/image-labeling/custom-models/android).

<table>
<tr>
 <td><img src="https://github.com/deckerst/aves/assets/59477313/cafbd063-eb76-4b5d-8617-7eccce89e841">
 <td><img src="https://github.com/deckerst/aves/assets/59477313/eb7fb66c-ffa6-414d-a88c-d2171fdfb887">
</table>

As you can see on these screenshots, if we bundle the entire model on the app, of course the size will increase quite a bit, but we don't have to depend on any GMS spyware! Moreover, we don't need to have a Firebase project or anything that could be privacy-invasive!

However, we'll still have Google related libraries (at least the `com.google.mlkit` one), so I don't hold out much hope that it will make it into the Libre/F-droid version.

What do you think about this idea?

**Comment by deckerst** [comment] 2023-06-29 20:12
I believe it's a duplicate of:
- #66

Google's ML kit is indeed the one I was considering to use, but I'll revisit available packages when I have time to look into ML stuff.

**Closed by deckerst** 2023-06-29 20:12 UTC
Labels: type:feature

**Comment by DodoLeDev** [comment] 2023-06-30 11:28
Oops! I missed this issue! Yeah it's a duplicate! 😅
