### ISSUE TITLE
More options for sorting by date

### ISSUE THREAD

**Issue by Ingegneus** [deckerst/aves#188] opened 2022-02-19 17:53 UTC
when clicking in the three dots on the top right, there is the view button. there are different options for sorting. it would be cool to 1) know what date is taken into consideration for the existing "Sort By Date" 2) change what date is used. for example everytime i change something on an image, the modification date chnages but i would like to sort with regards to the date the picture or video was taken. this would keep my gallery sorted no matter what

maybe give an option in the settings?

**Comment by Donkey-Doug** [comment] 2022-02-19 23:32
https://github.com/deckerst/aves/issues/97

**Comment by deckerst** [comment] 2022-02-24 01:34
> know what date is taken into consideration for the existing "Sort By Date"

The date is a composite, not relying on a single field. It looks for these (by precedence):
- Exif / DATETIME_ORIGINAL
- Exif / DATETIME
- XMP / xmp:CreateDate
- XMP / photoshop:DateCreated
- PNG / TIME / LAST_MODIFICATION_TIME
- Video / METADATA_KEY_DATE
- File / Modified date

> change what date is used

Selecting a specific field, say `XMP / xmp:CreateDate`, would bring unnecessary complexity.

Alternatively, some apps provide `date created` and `date modified` sorting options but it can be vague or misleading. For example, `Exif / DATETIME` is technically a modification date, but users may think `date modified` refers only to the file itself, not metadata.

Also, with modern Android storage permissions, the file modification date is out of control and may change in unexpected way, cf #111.

> the modification date chnages but i would like to sort with regards to the date the picture or video was taken

As I explained above, a metadata date has precedence over the file date, so the order should stay stable if the picture/video has a metadata date. This is usually the case for media taken with the camera, and screenshots too. Also, when rotating/tagging/rating in Aves an image that has no metadata date yet, the app will automatically assign it a metadata date with the current file date, so the "sort by date" order will be preserved.

If you deal with images that have no metadata date, you can assign them one in Aves (individually via the `Info` page menu, or collectively via the `Collection` page selection menu).

I think your request is a duplicate of #97 but let me know if I misunderstood, or if you have more questions about date handling.

**Closed** 2022-03-01 01:51 UTC
Labels: type:feature

**Comment by Ingegneus** [comment] 2022-03-01 08:55
Ok i see the problem now. My issue is, that i use syncthing to sync pictures between devices and it creates new files on my device, therefore the date is wrong. What i wanted was to be able to sort the images not by the creation date on the device, but by the date it was taken. From what you say though it seems almost impossible. I am aware that i can adjust the date by extracting it from the name, but that is not always possible.

**Comment by deckerst** [comment] 2022-03-01 09:55
Right, assigning them dates is the actual solution. If the title does not include one, you can also assign it from the current `file modified date`. Once assigned, the metadata date won't change when you sync files.
