### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by Subbarao6338** [deckerst/aves#166] opened 2022-01-23 04:15 UTC
- face detection and create collections using faces of people and pets
- recycle bin
- light theme
- add features like in Google photos

**Comment by deckerst** [comment] 2022-01-23 05:38
Wishlists are interesting, but it's more practical to split each feature request in its own issue.

Even better, before creating an issue you can search for existing issues asking for the same feature. You can show interest by adding a thumb up reaction 👍 to the opening post.

> face detection and create collections using faces of people and pets

Duplicate of #69 + additional issue for detection via AI?

> recycle bin

Duplicate of #12 

> light theme

Duplicate of #8

> add features like in Google photos

Please be more explicit.

**Closed by deckerst** 2022-01-23 05:38 UTC
Labels: close:duplicate, type:feature
