### ISSUE TITLE
Refresh rate is still 60 even though the option is set on 120

### ISSUE THREAD

**Issue by CopKillerAnarchist** [deckerst/aves#292] opened 2022-07-30 14:21 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem. If they are too private for this public space, feel free to [send them by email](mailto:gallery.aves@gmail.com).

**System information and logs:**
In the app, there are instructions in the `About` page > `Bug Report` section. After following them, paste here your system information and attach your logs.

**Additional context**

**Comment by deckerst** [comment] 2022-07-30 14:30
System information and logs:
In the app, there are instructions in the About page > Bug Report section. After following them, paste here your system information and attach your logs.

**Comment by CopKillerAnarchist** [comment] 2022-07-30 14:55
I'm sorry for being stupid but how exactly do I share the logs. They get saved to a txt. file that I'm unable to share here,unlike other types of medias.

As for system info:
Aves version: 1.6.11-izzy (Build 1077)
Flutter version: 3.3.0-0.0.pre (Channel beta)
Android version: 12 (SDK 31)
Android build: LE2111_11_C.61
Device: OnePlus LE2111
Mobile services: ready
System locales: en_US, en_GB, ro_RO
Aves locale: system -> en
Installer: com.looker.droidify

**Comment by deckerst** [comment] 2022-08-02 10:31
Related: https://www.androidheadlines.com/2022/04/oxygenos-change-causes-refresh-rate-drop-60hz-oneplus.html

**Comment by CopKillerAnarchist** [comment] 2022-08-03 07:22
1. Most apps I have make use of the 120hz refresh rate. However I have noticed some other apps with the same problem(only 60hz) like Twidere-X,Fritter(both Twitter clients),Kodi. Otherwise they all work as intented.
2.No matter which option I set(low,default,high) Aves Gallery is capped at 60 fps. 

As for screen being choppy I only meant relatively. After spending so much time on 120hz dropping down to 60 is jarring to say the least.

I'll paste the logs from my pc later today. It won't allow me to do it from my phone at all. Don't know why but it doesn't really matter either way.

**Comment by deckerst** [comment] 2022-08-26 07:32
Possibly related:
- https://github.com/flutter/flutter/issues/103847
- https://github.com/flutter/flutter/issues/75399
- https://github.com/flutter/flutter/issues/65795
- https://github.com/flutter/flutter/issues/88858

**Comment by caveman1973** [comment] 2022-09-15 21:14
Scrolling through photos ain't smooth.

I'm using a Google Pixel 5 with grapheneOS (Android 13). Same happened with Android 12.

**Comment by TheMysticS** [comment] 2022-10-27 08:26
> Sometimes the log export fails, and the exported file is empty (0 bytes). In that case, i think GitHub doesn't allow attaching it. But otherwise you should be able to attach it to the comment.
> 
> I'm not sure what this issue is about. You mention 2 different things:
> 
> 1. "screen is really choppy" which can be the case if there are some performance issues, whatever the selected refresh rate. For example I've noticed that scrolling through thumbnails that are not cached and that are derived from heavy files can easily lead to choppiness. It can also depend on the device performance, of course. I'm aware of this but I don't have a solution at the moment.
> 2. "refresh rate is still 60 even though the option is set on 120". I don't have a high refresh rate device to test it myself, and I've read that some manufacturers do not allow all 3rd party apps to use refresh rate higher than 60, even if the app requests it (they have a whitelist to allow some apps only). I don't know what's the policy on your OnePlus. Do you use a custom ROM, by the way?
> 
> To distinguish the refresh rate selection issue from general performance issues, i'd need to know whether 1) other 3rd apps have access to high refresh rate on your device, and 2) Aves feels like 60 FPS or worse, when you select the default refresh rate.

I have tried the app in multiple high-end devices. Scrolling is indeed jittery. It isn't smooth at all. This problem is specific to this app because the problem isn't there with any of the other gallery apps (I have about 20 of them installed). Too much stuttering when scrolling through pictures and videos. It is bad enough to make the experience poor and look for alternatives. Hope you would find the cause and fix it because the app looks very promising (animations are beautiful).

**Comment by deckerst** [comment] 2022-10-27 08:48
Thanks for the feedback. There was an issue in the framework used by Aves that was making the app stutter more in recent releases. Aves v1.6.7 to v1.7.0 had that framework issue, but v1.7.1 should be better.

**Comment by TheMysticS** [comment] 2022-10-27 08:53
> Thanks for the feedback. There was an issue in the framework used by Aves that was making the app stutter more in recent releases. Aves v1.6.7 to v1.7.0 had that framework issue, but v1.7.1 should be better.

I'm on version 1.7.1 and it (stuttering) still is quite bad. It may be better than previous versions, but there is still a lot of improvement required.

An in-app purchase option within Google Play Store to support development would be nice.

Once the stuttering issue is fully sorted out, I will come back with feedback on other aspects that would help in improving this app.

**Comment by deckerst** [comment] 2022-10-27 08:57
> An in-app purchase option within Google Play Store to support development would be nice.

I won't add an in-app purchase in the app. If you wish to donate, [it's already possible](https://github.com/deckerst/aves#donations).

**Comment by deckerst** [comment] 2024-06-20 21:01
I tried the app on a 120Hz display and it's clearly at 120Hz, so for OP issue of limited rate that's likely a limitation controlled by OnePlus Android flavour. For others who feel the app stutters, that's a different issue of performance. In any case I'll close this issue which is related to display refresh rate.

**Closed by deckerst** 2024-06-20 21:01 UTC
Labels: type:bug, bug:works-for-me, P3, oem:oneplus, android-api:31, bug:waiting-for-dependency
