### ISSUE TITLE
HEIC pictures won't display on specific resolutions

### ISSUE THREAD

**Issue by pikatchu2k3** [deckerst/aves#411] opened 2022-11-25 14:37 UTC
Hello, 

I am facing a problem with HEIC or AVIF pictures, which aren't shown on AVES or Google Fotos. 
The problem is, that pictures which have a resolution 3000x4000 or 4000x3000 can't be displayed. 
This problem can't be solved by clearing the EXIF data of the pictures. 
But reducing the resolution of pixels with a tool on my PC,, these files are visible afterwards. 

For converting my jpg images I tried imagemagick and libheif without any edits. Just pure conversion from jpg to AVIF or HEIC. 

This might be a general problem with android and HEIC/AVIF formats. There doesn't seem to be solution in the web atm. 

Device 
Pixel 7 pro with android 13.

Files: 
...300.HEIC is working but ...320.HEIC is not working. 
https://easyupload.io/m/ycpwc3

**Comment by deckerst** [comment] 2022-11-25 17:05
Decoding and displaying HEIC and AVIF files is not up to Aves, it's up to the codecs on the device. So if your device fails for these files (which seems to be the case as Google Photos fail too), there's nothing I can do to help.

That said, the files are not corrupted (because Aves render them fine on my device), but they're a bit weird. They are multi-page HEIC files, with twice the same image.

The "multi-page" overlay on the thumbnail:
<img width="300" src="https://user-images.githubusercontent.com/13898333/204029158-1200e89c-3965-4f12-9389-55f435e4caa5.png" />

The "multi-page" scroller in the viewer:
<img width="300" src="https://user-images.githubusercontent.com/13898333/204029163-1669bfa2-da9b-42e2-af6f-91c5a273fcf9.png" />

I'll close this issue because I think the problem is out of Aves scope. The only thing I can suggest is to revise your imagemagick / libheif command lines to generate more standard files.

**Closed by deckerst** 2022-11-25 17:05 UTC
