### ISSUE TITLE
Support crop images

### ISSUE THREAD

**Issue by atbest** [deckerst/aves#460] opened 2022-12-23 10:13 UTC
I am aware that aves is a excellent image viewing app, but not editing software. While mobile apps are not suitable to do extensive image processing, some easy and quit editing like crop is feasible and handy if aves can do. Using a third app is somehow complicated.

I found several image cropping libraries in pub.dev including [image_cropper](https://pub.dev/packages/image_cropper) and [image_crop](https://pub.dev/packages/image_crop). Both libraries are open sourced and sufficient for image cropping. I am wondering if you can use anyone of them or your own library to allow image cropping directly in aves.

Thanks.

**Comment by deckerst** [comment] 2022-12-23 10:22
> Using a third app is somehow complicated

Please elaborate.

**Comment by atbest** [comment] 2022-12-23 10:57
Well, the user experience are different. Most importantly, you will have to install one more app that can read and write external storage.

**Comment by deckerst** [comment] 2022-12-23 11:07
Funny you should say that, because using an external app for edition is so
smooth that several people have mistakenly thought that Aves included an
editor. Aves was opening the file with another app installed on their
device and they didn't realize it.

**Comment by atbest** [comment] 2022-12-23 12:32
Maybe they cannot, but I can clearly see the difference.

**Comment by deckerst** [comment] 2022-12-23 16:55
Anyway, I was interested in your point of view, but this is a duplicate of #17.

**Closed by deckerst** 2022-12-23 16:55 UTC
Labels: type:feature
