### ISSUE TITLE
amélioration étiquettes

### ISSUE THREAD

**Issue by Bebarr** [deckerst/aves#815] opened 2023-11-21 18:11 UTC
Bonjour, 
Merci beaucoup pour cette appli!
J'aimerais cependant pouvoir catégoriser mes étiquettes pour une meilleure classification des fichiers.

Par exemple, une catégorie saison pour les étiquettes hiver, printemps, autonome...

![Screenshot_2023-11-21_19-08-57](https://github.com/deckerst/aves/assets/46008532/fb0c6994-ecfb-4469-8212-8c2a40ca9a80)

Merci d'avance

**Comment by deckerst** [comment] 2023-11-21 18:26
It's not clear to me whether you wish the app:
1) to suggest tags (like the seasons) when adding tags, __or__
2) to allow users to group their existing tags within another "super-tag" (which is only defined in Aves, for organization in the app).

If it's 2), I suppose it's conceptually similar to nested albums, but for tags:
- #268

**Comment by Bebarr** [comment] 2023-11-22 09:08
Oui vous avez tout compris.
Comment débloquer le mode "super-tag" ?

**Comment by deckerst** [comment] 2023-11-22 18:51
Things like nested albums (or nested tags) are not supported yet. It's something I'd like to implement, but it's unlikely to happen in the short term.

I'll close this issue as a duplicate of the one referenced above.

**Closed by deckerst** 2023-11-22 18:51 UTC
Labels: type:feature

**Comment by Bebarr** [comment] 2023-11-22 20:01
> Things like nested albums (or nested tags) are not supported yet. It's something I'd like to implement, but it's unlikely to happen in the short term.
> 
> I'll close this issue as a duplicate of the one referenced above.

Ok je comprend. Je vais attendre les mise à jour patiemment :)
