### ISSUE TITLE
Rotate corrupts files

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#40] opened 2021-01-04 04:48 UTC
Rotating an image in aves makes the file corrupt. The image cannot be viewed in aves or other gallery apps.

**Comment by deckerst** [comment] 2021-01-07 01:36
I couldn't reproduce the issue, after trying with all these combinations:
- file format: JPG / PNG / WEBP
- storage volume: primary / SD card
- Android version: 8.0 / 10 / 11

I noticed there's a minor issue (the viewer sometimes does not refresh after rotating), but in any case no file got corrupted.

To investigate further I would need more details from you:
Does it happen all the time or randomly?
When it happens, is the file on the primary volume or something else?
Is the folder containing the file a special folder, like "Downloads"?
What is the file format?
Does Lineage OS have a different permission system, compared to vanilla Android?

**Comment by deckerst** [comment] 2021-01-17 06:23
I will close this issue but feel free to reopen it if you can provide further details.

**Comment by deckerst** [comment] 2023-06-21 16:52
Thanks for letting me know.

Could you paste here your environment info and logs (following instructions in `About` > `Bug Report`)?

Also, did it happen just once? several times randomly? all the time?

**Comment by DodoLeDev** [comment] 2023-06-29 14:15
I faced a similar issue while tagging videos:
Sometimes (it's quite rare for that to happen), when I tag mp4 videos, Aves returns `Success!`, but the file is no longer readable (with a big `Zut!`)

**Comment by deckerst** [comment] 2023-07-10 21:24
@a1danial do you use a custom ROM or some special security/memory features?

Also, do you know whether it happened when memory or storage was low?

I tried to reproduce by editing several hundreds files multiple times and I can't reproduce the issue :/

**Closed** 2023-09-19 06:35 UTC
Labels: type:bug, edition, metadata, bug:works-for-me, P0, android-api:33
