### ISSUE TITLE
Custom grouping and sorting for albums

### ISSUE THREAD

**Issue by RafeeDaBoy** [deckerst/aves#276] opened 2022-06-22 17:46 UTC
**Is your feature request related to a problem? Please describe.**
Currently albums can be sorted by name, date and item number and grouped by tier and storage volume.

**Describe the solution you'd like**
Allowing to reorder albums by just dragging them would really useful as well as creating custom groups would be really useful.

**Comment by deckerst** [comment] 2022-06-26 07:54
1) custom sort: duplicate of #231 
2) custom groups: I won't do that, but there's a request for nested albums #268

**Closed by deckerst** 2022-06-26 07:54 UTC
Labels: close:duplicate, type:feature
