### ISSUE TITLE
Grid preview when zooming

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#214] opened 2022-03-28 21:08 UTC
I believe the grid preview when zooming used to show how many squares would fit onto the screen. That does not work anymore:

https://user-images.githubusercontent.com/50382414/160487492-0a759003-be21-4b31-8398-a63fba300e72.mp4

**Comment by deckerst** [comment] 2022-03-29 01:37
The preview grid you see when scaling can help get a feel of how the desired thumbnail size will repeat, but it's not meant to represent the exact grid you will get for this particular screen width. It has always been centered and measured from the scaled thumbnail, and that didn't change.

This preview grid reflects the fact that Aves does not work with a desired number of columns, but rather a desired thumbnail size. This is especially meaningful when the app is in a resizable screen (like the app pop-up view available on Samsung OneUI).

I will close this, as the intended behaviour did not change and it's not a bug. I wonder why you interpreted it differently before.

**Closed by deckerst** 2022-03-29 01:37 UTC
Labels: type:bug
