### ISSUE TITLE
Add Shavian in Weblate | 𐑨𐑛 ·𐑖𐑱𐑝𐑾𐑯 𐑦𐑯 ·𐑢𐑧𐑚𐑤𐑱𐑑

### ISSUE THREAD

**Issue by JackknifedJuggernaut** [deckerst/aves#1253] opened 2024-10-21 20:18 UTC
**Is your feature request related to a problem? Please describe**
No, it's related to localization.

**Describe the solution you'd like**
Add Shavian-script version of English – the “[en_Shaw](https://hosted.weblate.org/languages/en_Shaw)” locale, specifically – in Weblate; I can't do that myself.

**Additional context**
I would like to translate the project to Shavian.

 
**¿𐑦𐑟 𐑘𐑹 𐑓𐑰𐑗𐑼 𐑮𐑦𐑒𐑢𐑧𐑕𐑑 𐑮𐑦𐑤𐑱𐑑𐑩𐑛 𐑑 𐑩 𐑐𐑮𐑪𐑚𐑤𐑩𐑥? 𐑐𐑤𐑰𐑟 𐑛𐑦𐑕𐑒𐑮𐑲𐑚**
𐑯𐑴, 𐑦𐑑'𐑕 𐑮𐑦𐑤𐑱𐑑𐑩𐑛 𐑑 𐑤𐑴𐑒𐑩𐑤𐑲𐑟𐑱𐑖𐑩𐑯.

**𐑛𐑦𐑕𐑒𐑮𐑲𐑚 𐑞 𐑕𐑩𐑤𐑵𐑖𐑩𐑯 𐑿'𐑛 𐑤𐑲𐑒**
𐑨𐑛 ·𐑖𐑱𐑝𐑾𐑯-𐑕𐑒𐑮𐑦𐑐𐑑 𐑝𐑻𐑠𐑩𐑯 𐑝 ·𐑦𐑙𐑜𐑤𐑦𐑖 – 𐑞 «[en_Shaw](https://hosted.weblate.org/languages/en_Shaw)» 𐑤𐑴𐑒𐑭𐑤, 𐑕𐑐𐑩𐑕𐑦𐑓𐑦𐑒𐑤𐑦 – 𐑦𐑯 ·𐑢𐑧𐑚𐑤𐑱𐑑; 𐑲 𐑒𐑭𐑯'𐑑 𐑛𐑵 𐑞𐑨𐑑 𐑥𐑲𐑕𐑧𐑤𐑓.

**𐑩𐑛𐑦𐑖𐑩𐑯𐑩𐑤 𐑒𐑪𐑯𐑑𐑧𐑒𐑕𐑑**
𐑲 𐑢𐑫𐑛 𐑤𐑲𐑒 𐑑 𐑑𐑮𐑨𐑯𐑟𐑤𐑱𐑑 𐑞 𐑐𐑮𐑪𐑡𐑧𐑒𐑑 𐑑 ·𐑖𐑱𐑝𐑾𐑯.

**Comment by deckerst** [comment] 2024-10-22 11:38
I've just added the language to the project on Aves. I'm surprised it wasn't available to you. Anyway, let me know how it goes.

**Comment by deckerst** [comment] 2024-10-22 23:27
@JackknifedJuggernaut I've added the locale files from code. Weblate seems usable, but it is confused and fails to gather all the project components under the same "English (Shavian)" language. Instead, the translation is split as follows:
- https://hosted.weblate.org/projects/aves/app-android/en_SHAW/
- https://hosted.weblate.org/projects/aves/app-main/en_Shaw/
- https://hosted.weblate.org/projects/aves/store-short-description/en-Shaw/
- https://hosted.weblate.org/projects/aves/store-full-description/en-Shaw/

You can contribute these translations. Do not attempt to create translations for the other component/language combinations.

**Comment by deckerst** [comment] 2024-10-25 19:07
@JackknifedJuggernaut thanks for your contributions! I'm integrating your translation now.

It's all good on Aves side, but there are some basics that are not covered as this is an unusual transliteration, most importantly for the dates and units.

Could you please give me the transliteration for the following?
- Months (long form): January, February, March, April, May, June, July, August, September, October, November, December
- Months (short form): Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
- Days (short form): Mon, Tue, Wed, Thu, Fri, Sat, Sun

**Comment by benji78** [comment] 2024-11-01 11:10
Aves description in the IzzyOnDroid F-Droid repo is in Shavian language instead of english!

**Comment by deckerst** [comment] 2024-11-01 11:23
Haha, that's a funny side effect ^^

I'm off for a few days. In the meantime maybe you can check this with Izzy himself, see why they pick the locale `en-Shaw` rather than `en-US`.

**Comment by TheLastProject** [comment] 2024-11-01 23:51
Ping @IzzySoft :)

**Comment by IzzySoft** [comment] 2024-11-02 00:32
We just pick the entire fastlane tree, not specific locales. If the wrong one shows up in the client, that would be an error in either fdroidserver or fdroidclient then (as @benji78 tested on droid-ify as well, it must be fdroidserver then generating it wrong – but then the web repo browser should have the same issue).

If you talk about the repo-browser web interface: that looks fine to me (just tested: shows DE to me by default as my browser says so, shows en-US when requested. Setting the preferred language to en-US results in en-US as well.

REmains the question of what language preferences were set on the client? I've now checked the repo browser, Neo Store, F-Droid's official client – I cannot reproduce that, all of them show the English data fine.

**Comment by benji78** [comment] 2024-11-02 12:17
Is there a way to set en_us as the default? Otherwise adding Australian as a copy of US localisation could be a possible workaround.

**Comment by IzzySoft** [comment] 2024-11-02 14:03
I guess there's nothing Thibault or I could do (apart from adding all possible localizations or remove all except for `en-US` and causing other complaints). If your "preferred language" is not present, `en-US` should be the default language picked – or rather, in this order: `en-GB` => `en` => `en-US` (similar with `de-AT` => `de` => `en-US`). But with `en-GB` set, and `en-US` present, `en-Shaw` should not be picked at all. Which is something the clients should take care for.

That said, what do you get visiting [Aves at IzzyOnDroid's repo browser](https://apt.izzysoft.de/fdroid/index/apk/deckers.thibault.aves) with your default setting of `en-GB`? I've just tried and got German (as my browser has `de` defined as a fallback language, and `de` is available).

**Comment by licaon-kter** [comment] 2024-11-04 09:50
I saw https://expressional.social/@james/113403761943038968 but can't repro the issue in F-Droid Client

the website looks affected though https://f-droid.org/en/packages/deckers.thibault.aves.libre/

@deckerst from what I understood maybe you need to add the country code too, eg: `en-US-Shaw`

**Comment by deckerst** [comment] 2024-11-04 10:02
I think I'll try something else: to rename the fastlane "en-US" folder to "en" (because it's the intended default anyway), and to configure Weblate so that it targets the same locale as before.

**Comment by IzzySoft** [comment] 2024-11-04 11:44
Note that `en-US` is considered mandatory (at least by F-Droid) as it's the fallback for all locales not present (same at IzzyOnDroid) – so **renaming** `en-US` to `en` would have implication for a lot of locales. Not sure if they'd show anything at all then, unless explicitly covered by your fastlane. Making a symlink would work for F-Droid, and if you want to go that path I could establish that here manually.

**Comment by deckerst** [comment] 2024-11-04 18:22
@IzzySoft Thanks for the heads-up about the required locale. So indeed renaming is not the way.

I am disappointed that these systems require this particular default `en-US`, but do not leverage it as expected. We witness this issue with `en-Shaw`, but it would be the same thing if it was `en-CA`, or anything coming alphabetically before `en-US`. It's not as obvious but it's just as wrong.

> Making a symlink would work for F-Droid, and if you want to go that path I could establish that here manually.

Not sure I understand. Did you mean 1) submitting a PR to Aves to add the symlink, or 2) tweaking IzzyOnDroid / F-Droid to act as if there was a symlink in Aves repo fastlane tree?

Given past experience with Weblate, I'd say it will yell and break if it finds both `en` and `en-US` in the fastlane tree, because the Weblate project is already configured to treat both as the same locale. Note that in Weblate the Aves project is split in different components for different language/environments (Android, Dart, fastlane) where locales are encoded in different ways, so it's a bit fiddly to make Weblate happy with these locale equivalence.

**Comment by IzzySoft** [comment] 2024-11-04 21:57
> I am disappointed that these systems require this particular default en-US, but do not leverage it as expected. We witness this issue with en-Shaw, but it would be the same thing if it was en-CA, or anything coming alphabetically before en-US. It's not as obvious but it's just as wrong.

And there I thought the default was **fixed** to `en-US`. Strange enough with the "US" (one would expect a simple `en` instead, not country/region-specific). But then taking something random? Oof.

Symlink: IoD and FD deal differently with Fastlane. F-Droid builds from source, so it has your repo checked out and can simply copy the fastlane structure over. IoD on the other hand takes the APK you provide at releases, and utilizes the Forgejo/Github/GitLab APIs to fetch Fastlane. Unfortunately, the Github API is very strange when it comes to symlinks; I couldn't yet find a way to handle those. So at IoD, I'd simply add the symlink manually (our API would ignore it when pulling Fastlane, so it would persist) – while for F-Droid, the symlink must be in your repo as nobody can reach the ultra-secret build server we mere mortals are not supposed to know where it is located (if you don't understand this reference, I can solve the riddle for you by mail) to place the symlink there…

> because the Weblate project is already configured to treat both as the same locale.

Ouch. Then we have a problem here: you can neither use a symlink nor have `en` as a copy, as Weblate would go nuts… Well, not an issue with IzzyOnDroid (as here the symlink would only be locally on our side). But no way to get that fixed for Aves-libre at F-Droid.

Well, if you want me to, I can at least fix it for IzzyOnDroid, making a `ln -s en-US en` in Aves' fastlane tree here. Just let me know.

**Comment by deckerst** [comment] 2024-11-04 22:12
With regards to F-Droid, do you think it's something they could look at? It seems to me their locale resolution strategy is broken, especially with such a required default.

An easy band-aid on my side would be to create `en-CA` (anything before "Shaw") and copy there the content of `en-US`. I'm hesitant to do it though, because it's not addressing the root cause.

**Comment by IzzySoft** [comment] 2024-11-04 23:50
> With regards to F-Droid, do you think it's something they could look at? It seems to me their locale resolution strategy is broken, especially with such a required default.

I doubt they'd see that as priority. There're issues in this context open for 5 years and more (e.g. never replace a `1.jpg` by a `1.png` in your fastlane; once deployed, you can never get rid of a screenshot; and you'll have to wait weeks or even months or longer for someone to clean that up manually, as.. well, I told you the build server is secret, did I? So who'd do the cleanup?). There's a comparable bug in the handling at IoD, but a) I'm fast to clean up when made aware of it, and b) with IoD you could do that yourself by dropping both `1.*` files from your fastlane, push a release, and add the correct `1.*` file back (or simply rename it to `1a.*` so it gets fixed with a single release)… (I really need to kick the "screenshot optimizing feature" that converts PNG to JPG on certain conditions, so the cleanup would work properly – but yeah, I feel "bandwidth" an important factor – environment-wise as well as for not-so-privileged folks).

As for `en-CA`: I could symlink to that, too :stuck_out_tongue_winking_eye: But yeah, would not address the root cause. My question there is still: does it only affect the official F-Droid client – or all clients? I doubt it's a fdroidserver issue (the index simply holds all the locales; which to choose is the task of the client). Maybe other clients adopted the logic from the fdroidclient initially. Should the very problem show up e.g. with Neo Store, I'm confident Toni would investigate if we'd reach out to him.

**Comment by deckerst** [comment] 2024-11-05 07:43
Thanks for all the details. Then I won't expect resolution from their side and will try the band-aid™ for the next release. 

As for other clients, actually I've just tried it myself (I have neo store and my first locale is en-uk) and... I see Shavian!

If I may, please do not fix it on IoD with the symlink, so we can quickly assess the efficacy of the band-aid™ next time (your repo quickly picks up new releases while F-droid takes forever). And in the meantime people will get to discover Shavian... Or am I too easygoing?

**Comment by licaon-kter** [comment] 2024-11-05 08:14
> My question there is still: does it only affect the official F-Droid client – or all clients? 

Wat?

**Comment by IzzySoft** [comment] 2024-11-05 14:26
> Wat?

Read above :wink:

> please do not fix it on IoD with the symlink

OK, I'll keep my fingers away then.

**Comment by licaon-kter** [comment] 2024-11-05 14:35
> Read above 😉

Read above above: https://github.com/deckerst/aves/issues/1253#issuecomment-2454245090

**Comment by deckerst** [comment] 2024-11-05 15:42
> @deckerst from what I understood maybe you need to add the country code too, eg: en-US-Shaw

I missed this suggestion. It's actually something I could try, as i think I know a way to make Weblate happy with this configuration.

**Closed** 2024-11-08 18:38 UTC
Labels: type:feature

**Comment by deckerst** [comment] 2024-11-11 21:37
@JackknifedJuggernaut thanks for the interesting points

> the language list in settings contains “English”, when for the matter of fact it's “English (United States)

True. But as soon as another dialect will be complete in Weblate, I'll clarify the dialects in the app. For now, "English" is sufficient as it refers to the worldwide default, i.e. US English.

> what do you think about “en-XW-Shaw” IETF tag?

Thanks for the suggestion, I'll use it.

> antepenultimate

Nice.

> consider adding to Weblate strings for the following phrases:

    “GitHub” in the “About“ page
    “World Atlas” in the “About” page
    Open-source licenses' names in the “About” page
    Text in the “Licenses” page (“Show all licenses” button)
    License texts in the “Licenses” page
    File format names in the media viewing page (JPEG, PNG, WEBM, etc.)

Some of these are automatically generated (the licenses), some shouldn't be translated or even transliterated (the file formats, which most often match file extensions in latin). The products and brands are debatable, but for now I don't intend to make them translatable, especially the ones you pointed, since GitHub is a pure English (Latin) site.

> Abbreviated names of information units (KB, MB, GB, etc.)

Fair enough. Maybe in the future.

> Text in the metadata section of the media viewing page (Exif, Huffman, JFIF, etc.)

Not gonna happen. That text comes from a dependency I use.

> Text in the “Explorer” page (“Internal shared storage”, “Download”, etc.)

It's actually coming from your OS and storage labels. For "Download" it's trickier: as a folder I respect the folder label on storage, but as an album it's a standard album so it gets translated (like `Camera` and `Screenshots`).

> And think about adding months and days to Weblate, so that you don't have to ask manually.

Nope. Most languages are already covered by the library that needs these translations. Only Shavian was missing because it's niche.

> Actually, I wanted to ask something: are information units in Aves decimal or binary? If it's the former, there's an ambiguity; if it's the latter, the names should be “KiB”, “MiB”, “GiB”, etc. Or maybe you could add an option for both in the settings.

Correctness is nice, but it sometimes needs to yield in favour of familiarity. So yes it's binary, but people are used to see KB and MB. Providing extra settings for everything is not a solution.

**Comment by deckerst** [comment] 2024-11-23 10:56
@IzzySoft @licaon-kter Following the release of Aves v1.11.18, I've checked the fix and it seems it worked for F-Droid repo but not for Izzy's.

I've checked with `F-Droid` standard app and `Neo Store`, and they behave the same:
- when I set my device in `English (US)` it shows the description in English as expected for both `Aves Libre` (in F-Droid repo) and `Aves` (in Izzy repo),
- when I set my device in `English (UK)` it shows the description in English as expected for `Aves Libre` (in F-Droid repo), but it mistakenly shows it in Shavian for `Aves` (in Izzy repo).

In Aves source, the Fastlane folder for Shavian is now `en-XW-Shaw`, which is alphabetically after the standard `en-US` folder, so I really wonder why these client apps pick that locale, and *only* for Izzy's repo.

**Comment by licaon-kter** [comment] 2024-11-23 12:42
Maybe Izzy didn't get a chance to look at the new metadata yet, I'd wait

**Comment by IzzySoft** [comment] 2024-11-23 17:36
Fastlane is pulled along with releases here. Bug let me compare the structures, maybe parts of the old fastlane structure (i.e. the previous Shavian tree) remained (@licaon-kter does F-Droid meanwhile clean up the fastlane tree before integrating the new one? I only remember issues with screenshots remaining in the tree, but don't remember how an entire locale disappearing is handled).

And yupp, indeed: `en-Shaw` was still there. Seems like "cleaning up locales removed upstream" is not handled here (that's still on the todo list: separating Fastlane pulled from upstream from "local metadata"). I've removed that locale now. Can you check again after the sync completed (in about 2 hours from now), Thibault?

**Comment by licaon-kter** [comment] 2024-11-23 18:02
I only recall screenshot issues yes

**Comment by IzzySoft** [comment] 2024-11-23 18:37
So I wonder how that additional locale got cleaned up. But hey, important thing is it got cleaned up, right? :wink: Though it would help to understand, so we can give people the right recommendations. Thanks for clarifying!

**Comment by deckerst** [comment] 2024-11-23 19:31
All is well now. Thanks for cleaning up the obsolete locale.
