### ISSUE TITLE
Finger hold time to be same for album and image for multiple selection

### ISSUE THREAD

**Issue by NDR-113** [deckerst/aves#477] opened 2023-01-04 17:25 UTC
**Is your feature request related to a problem? Please describe.**
Yes. The finger hold time to go into multiple album selection mode is shorter than the one to go into multiple image selection mode (it seems like it). This results in often accidentally going into multiple album selection mode by accident when slowly scrolling. This doesn't happen when scrolling individual images nearly as often.

**Describe the solution you'd like**
Time should be the same for both situations for consistency/predictability. Suggestion would be to have the individual image one for both as it is less prone to accidents and it still feels responsive/quick enough.

**Comment by deckerst** [comment] 2023-01-07 10:17
You made me doubt so I double-checked, and the it's the same time for both cases. Actually, it's the same code that handle both, so it can't be different.

I also tried to reproduce your issue by slowly scrolling on both pages and they react the same.

I'll close this because, as I said, the same code handles both cases. But feel free to comment later if you have another idea regarding the cause of what you're experiencing.

**Closed by deckerst** 2023-01-07 10:17 UTC
Labels: type:feature

**Comment by NDR-113** [comment] 2023-01-08 16:40
Ok, strange, it does feel faster in the albums, thanks for checking out. 

Ok so what i experience often is when you're in album view and scroll down. Then to stop the downwards movement you tap the screen. If you don't lift the finger quickly, it goes into selection mode. I have the impression that in that situation it might be better to allow leaving the finger on the screen without it going into multiple selection mode. That way we can do a followup scroll without the need to lift it. So to make it short: would it maybe be better that in order to go into multiple selection after a scrolling movement we have to lift the finger and then tap again?

Also another suggestion (sorry if it's only marginally related, but it's still about multiple selection, i can make a new thread if you'd prefer). The idea is when going into multiple selection (album or images) immediately show the top bar - so without the need to scroll down so that it shows up. The reason is that when we go into multiple selection we are going to need that top bar for sure, so it might as well show up.

**Comment by deckerst** [comment] 2023-01-08 17:03
> would it maybe be better that in order to go into multiple selection after a scrolling movement we have to lift the finger and then tap again?

> when going into multiple selection (album or images) immediately show the top bar

I agree with both. Actually the second one has been on my mental todo list for some time. Don't know when I'll get to it though ^^

**Comment by deckerst** [comment] 2023-01-13 14:31
Done both.

**Comment by NDR-113** [comment] 2023-01-13 15:13
That was fast, nice.
