### ISSUE TITLE
Renaming creates non-existing duplicate

### ISSUE THREAD

**Issue by Donkey-Doug** [deckerst/aves#107] opened 2021-10-13 08:26 UTC
Earlier I renamed a few photos using Aves. I noticed these thumbnails were shown twice. One had the old name and one the new. However, the old file would not show an image when opening, but instead shows a black screen with a "this file does not exist" message.

**Comment by deckerst** [comment] 2021-10-13 08:31
Does it happen all the time? some of the time?
Do these ghost files automatically get cleaned up after a while? after a fresh restart of the app?

**Comment by Donkey-Doug** [comment] 2021-10-16 00:35
Update: Also happens sometimes without manual rescan.

**Comment by deckerst** [comment] 2021-10-16 00:42
Could you please attach app logs?

**Comment by deckerst** [comment] 2021-10-17 05:16
It seems to happen only when renaming media 1) owned by other packages and 2) on Android 10. Possibly only happening in the Download folder (I couldn't confirm that on the emulator). Anyway, now that I can reproduce it, I'll try and fix it.

**Comment by Donkey-Doug** [comment] 2021-12-13 03:18
I do not think this is fixed:

[aves-logs-20211213_040955.txt](https://github.com/deckerst/aves/files/7700758/aves-logs-20211213_040955.txt)

**Comment by deckerst** [comment] 2022-01-18 02:49
Thanks for the report. I'll take a look.

This issue has a lot of history, so I'd like to recap what you experience:
- do you experience this issue consistently or randomly?
- does it happen on renaming, on moving, on deleting, on all 3?
- does it happen in various directories?
- some OEMs customize their ROM with some kind of "permission monitor" which makes it behave differently from standard Android. I'm aware of this on some Realme UI / ColorOS for Android 10. Maybe Xiaomi also adds similar bloatware. Do you know if that's the case on your device? If you have some way to disable this additional permission monitor (maybe in the "Developer options" settings), could you try and let me know if it makes a difference?

**Comment by deckerst** [comment] 2022-01-18 08:20
I'm not familiar with LineageOS, but apparently [another user has similar symptoms with LineageOS 17 / Android 10](https://gitlab.com/LineageOS/issues/android/-/issues/2327).
By the way, is your LineageOS build official or not?

**Comment by Donkey-Doug** [comment] 2022-01-19 00:16
My lineageos is unofficial, but that should not be a problem. The dev of my device is too lazy to compile and upload to lineage.

I think it only happens on renaming.

Maybe it only happens in the download directory. Not sure.

It seems to happen randomly.

**Comment by deckerst** [comment] 2022-03-07 08:08
In Aves v1.6.2, I revisited storage access for Android 10 and older.

The initial reason was a regression introduced in Aves v1.6.1, preventing write access specifically on Android 10. But I also found out a way to reproduce (and fix) on the Android Nougat emulator an issue that looked a bit like the one you described here.

My point is... maybe the bug you described is now fixed. I can't reproduce it on the Android 10 emulator, so I can't be sure, but I'm hopeful!

**Comment by Donkey-Doug** [comment] 2022-04-18 17:02
The bug is still present.

**Comment by kha84** [comment] 2022-09-15 14:49
I also have this bug. I copied a photo from one folder to another couple of times. The second time Aves asked me if I want to replace - I said yes. But as a result now Aves shows me 2 thumbnails for the very same photo. Both photos details are identical (including path). Rescanning or app restarting doesn't get rid of that duplicate

**Comment by deckerst** [comment] 2022-09-15 16:55
@kha84 your issue is different from this one. I created #335 to track it.

**Closed** 2022-11-04 18:36 UTC
Labels: type:bug, bug:worksforme, P5, rom:lineage-os, android-api:29, oem:xiaomi
