### ISSUE TITLE
Empty folders are deleted

### ISSUE THREAD

**Issue by Marmo** [deckerst/aves#578] opened 2023-04-08 11:58 UTC
**Describe the bug**
When deleting the last file in a directory, the directory is deleted, too.

**To Reproduce**
1. Create a folder
2. Put two images into it
3. Open the first image in Aves and send it to trash
4. The directory still exists (checked in file manager)
5. Open the remaining image and send it to trash
6. The directory is deleted, too (checked in file manager)

**Expected behavior**
The directory is not deleted.
My Scenario is: My Camera app puts its photos in a folder on the internal storage, from there they are moved to the SD card from time to time, so this directory is sometimes empty. Now I take photo and delete it instantly -> the camera app's target directory is deleted and the camera fails to save photos.

**System information and logs:**
Package: deckers.thibault.aves.libre
Aves version: 1.8.4-libre
Aves build: 9502
Flutter version: 3.7.7
Flutter channel: stable
Android version: 11
Android API: 30
Android build: 8901.4.A.0021.0 release-keys
Device: Fairphone FP3
Geocoder: ready
Mobile services: not available
System locales: de_DE, en_US
Aves locale: system -> de
Installer: com.google.android.packageinstaller
Error reporting: false

**Comment by deckerst** [comment] 2023-04-08 12:11
This is the intended behavior, not a bug. From *my* point of view, your camera app should be fixed so that it doesn't matter whether the directory already exists or not.

That said, i understand this is not a satisfactory answer to you. I don't want to add a setting for this, but what i could do is to keep the directory of the album if it is identified as an "app" album. In your case, is the camera app target directory in the `Apps` tier group in the `Albums` page?

**Comment by Marmo** [comment] 2023-04-09 08:01
Thanks for your explanation!

> In your case, is the camera app target directory in the Apps tier group in the Albums page

No, its just a subdir of the DCIM folder. You are right, my camera app (OpenCamera) could probably recreate the missing folder. My temporary workaround is to put an empty file into the folder which then prevents Aves from deleting the dir.

Imo deleting the dir with the last image is still not what I would expect (deleting an album=directory is available from the albums screen), but, of course, you are the developer so its your decision.

Thanks anyway for this great app!

**Comment by Marmo** [comment] 2023-04-09 08:05
Ah, just found out I can manually assign a folder to an app, maybe (as you said) this could be a hint for Aves not to delete it if empty. But my workaround works, so im am fine now 😉

**Closed** 2023-04-16 16:38 UTC
Labels: P4
