### ISSUE TITLE
Convert to still fails on galaxy ultra s24

### ISSUE THREAD

**Issue by catacgc** [deckerst/aves#1358] opened 2024-12-26 09:45 UTC
**Describe the bug**
Convert to still image fails on s24 ultra 

**To Reproduce**
1. Select the motion photo collection
2. Select any image(s)
3. Convert to still fails 

**System information and logs:**
[aves-logs-20241226_143855.txt](https://github.com/user-attachments/files/18251743/aves-logs-20241226_143855.txt)

Package: deckers.thibault.aves
Installer: com.android.vending
Aves version: 1.12.0-play, build 140
Flutter: stable 3.27.1
Android version: 14, API 34
Android build: UP1A.231005.007.S928BXXS4AXKA
Device: samsung SM-S928B
Support: dynamic colors=true, geocoder=true, HDR=true
Mobile services: ready
Connectivity: wifi, vpn
System locales: en_GB
Storage volumes: /storage/emulated/0/
Storage grants: /storage/emulated/0/Movies/, /storage/emulated/0/DCIM/, /storage/emulated/0/Download/Archive/
Error reporting: true

**Comment by deckerst** [comment] 2024-12-26 09:54
Can you provide a sample motion photo for which it fails?

**Comment by catacgc** [comment] 2024-12-26 10:26
And I just noticed that edit doesn't work either on .heic

**Comment by deckerst** [comment] 2024-12-26 11:26
Right, metadata editing is not supported for heic at the moment: 
https://github.com/deckerst/aves/wiki/Support:-Metadata-editing

I'll close this one as it is not a bug per se, but feel free to upvote/subscribe to this one: 
- #145

**Closed by deckerst** 2024-12-26 11:26 UTC
Labels: type:bug
