### ISSUE TITLE
Can't change video tags

### ISSUE THREAD

**Issue by xmha97** [deckerst/aves#348] opened 2022-10-09 19:50 UTC
Hi, I want to change the video location.
![Screenshot_2022-10-09-23-17-23-907_deckers.thibault.aves.jpg](https://user-images.githubusercontent.com/23485114/194776677-17119995-b674-4aca-a755-396734acfcb4.jpg)
Please add the feature below:
- Support edit video tags

**Comment by deckerst** [comment] 2022-10-09 20:25
Duplicate of #105

**Closed by deckerst** 2022-10-09 20:25 UTC
Labels: type:feature
