### ISSUE TITLE
Miui support and Mosaic View.

### ISSUE THREAD

**Issue by UniverseCodex01** [deckerst/aves#298] opened 2022-08-04 03:17 UTC
-Miui support:
Please add support to set lock screen wallpaper in miui, as we know miui don't works like AOSP to set wallpapers, miui use their Theme Manager app and this results in impossible to set lock screen wallpapers by 3rd party gallery but Devs can add support to gallery can detect Theme manager app and set lock screen wallpaper, for now, I know only one gallery That support miui fully and is Gallery - picture gallery by Photo Gallery Tools.

![IMG_20220804_000743](https://user-images.githubusercontent.com/93066706/182754635-f5aa1a01-8413-4f1d-b8b1-c2a0e96566a3.jpg)

![Screenshot_2022-08-04-00-08-03-628_com android thememanager](https://user-images.githubusercontent.com/93066706/182754648-effbc4f4-33e0-425a-be93-274b774292fb.jpg)

![Screenshot_2022-08-04-00-08-08-630_com android thememanager](https://user-images.githubusercontent.com/93066706/182754673-5f7a73a9-5eae-4301-9943-a1d57b71c1f1.jpg)

- Mosaic view:
Please add mosaic view to layout options, like Google photos, for the moment app only support list view and grid view but I want mosaic view because allow to see all picture content in thumbnail, with list view and grid view is necessary open picture to se all picture content.

EXAMPLE, GOOGLE PHOTOS SCREEN SHOT WITH MOSAIC VIEW OF PICTURES:

![Screenshot_2022-08-04-00-08-31-704_com google android apps photos](https://user-images.githubusercontent.com/93066706/182754690-bdb86faa-8f2f-495d-a4ee-cfc4208c6dc2.jpg)

![Screenshot_2022-08-04-00-14-18-357_com google android apps photos](https://user-images.githubusercontent.com/93066706/182755273-b2434493-0c4c-4459-822c-9f2895957bae.jpg)

![Screenshot_2022-08-04-00-14-32-497_com google android apps photos](https://user-images.githubusercontent.com/93066706/182755328-1d10068b-e859-4351-a917-e4c7c0703145.jpg)

**Comment by deckerst** [comment] 2022-08-04 08:56
Please [read this before opening issues](https://github.com/deckerst/aves/issues/234).

1) Miui support
Can you try [this](https://www.reddit.com/r/Xiaomi/comments/ikqofx/comment/g3mny3a/)? If this doesn't work, I suggest you petition Xiaomi to adhere to Android standards, or at the very least document their custom behaviours.

2) Mosaic view
Duplicate of #67.

**Closed by deckerst** 2022-08-04 08:56 UTC
Labels: type:feature
