### ISSUE TITLE
First character of sentence in info page display as tofu

### ISSUE THREAD

**Issue by CoelacanthusHex** [deckerst/aves#700] opened 2023-07-31 10:04 UTC
**Describe the bug**

First character of all sentences are tofu in info page

**To Reproduce**
1. Go to info page of any picture
2. See error

**Expected behavior**

The character displayed correctly

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem. If they are too private for this public space, feel free to [send them by email](mailto:gallery.aves@gmail.com).
![Screenshot_20230731-175702_Aves](https://github.com/deckerst/aves/assets/43064781/7500343c-9868-4f31-8bf5-800a55ab4013)
![Screenshot_20230731-175733_Aves](https://github.com/deckerst/aves/assets/43064781/17dccb8f-6b55-4c95-b426-53d96cfbb343)

**System information and logs:**
In the app, there are instructions in the `About` page > `Bug Report` section. After following them, paste here your system information and attach your logs.

Package: deckers.thibault.aves
Installer: null
Aves version: 1.8.9-izzy, build 10001
Flutter: stable 3.10.3
Android version: 12, API 32
Android build: lineage_apollon-userdebug 12 SQ3A.220705.004 70c11cd2b4
Device: Xiaomi M2007J3SC
Geocoder: ready
Mobile services: ready
System locales: zh_CN, zh_Hant_TW, en_US
Storage volumes: /storage/emulated/0/
Storage grants: 
Error reporting: false
[aves-logs-20230731_180222.txt](https://github.com/deckerst/aves/files/12213863/aves-logs-20230731_180222.txt)

**Additional context**

**Comment by deckerst** [comment] 2023-07-31 11:24
Thanks for the report!

If you change the language in Aves to English, do you have the issue?

If you change the primary locale in Android to English (instead of Chinese), do you have the issue?

**Comment by CoelacanthusHex** [comment] 2023-07-31 11:48
> Thanks for the report!
> 
> If you change the language in Aves to English, do you have the issue?
> 
> If you change the primary locale in Android to English (instead of Chinese), do you have the issue?

I can reproduce it with any combination of application language and android language with Chinese and English.

**Comment by deckerst** [comment] 2023-07-31 12:22
Damned. Then i fear this is an issue with your specific environment. You use Lineage, right? Are there some special settings when it comes to fonts?

This info section uses some special Unicode characters that are invisible but useful to indicate custom string direction in the context of right-to-left languages. These characters do not yield tofu for me (and I believe most users), that's why i think there's something special about your environment.

**Comment by CoelacanthusHex** [comment] 2023-07-31 12:43
> Damned. Then i fear this is an issue with your specific environment. You use Lineage, right? Are there some special settings when it comes to fonts?

Yes, I use custom font setting via fonts.xml. When I disable it, the problem disappears.

> 
> This info section uses some special Unicode characters that are invisible but useful to indicate custom string direction in the context of right-to-left languages. These characters do not yield tofu for me (and I believe most users), that's why i think there's something special about your environment.

It's weird, I just changed the font. These fonts should work fine in RTL environments. Can you provide the characters or related codes added here? I'd like to test to see if it works in other apps (I've had some font issues unique to the Flutter environment, so I suspect it might have something to do with the Flutter implementation).

**Comment by deckerst** [comment] 2023-07-31 12:51
Glad we found the cause.

Sure, I'll provide the details, but later (at work now).

**Comment by deckerst** [comment] 2023-08-01 17:50
@CoelacanthusHex here you are:
- [info text span building in Aves](https://github.com/deckerst/aves/blob/develop/lib/widgets/viewer/info/common.dart#L168),
- [the referenced unicode characters](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/foundation/unicode.dart).

I'll close this issue as it only exists because of your custom font settings. But feel free to comment if you have insights.

**Closed by deckerst** 2023-08-01 17:50 UTC
Labels: type:bug

**Comment by ksyx** [comment] 2023-08-01 19:24
Since some fonts are unaware of the combination and would do nothing with it, would it be possible to add an option to disable this behavior of preceding a FSI?

**Comment by deckerst** [comment] 2023-08-01 20:35
These characters do not represent glyphs, they are not supposed to be rendered. They are control characters, so I'm surprised that the font would be involved at all. I would expect the font system, text rendering library, etc. to be responsible.

@ksyx In any case, I won't provide that option. But if you also experience this issue, please paste here your environment details, and any custom font settings you may use.

**Comment by CoelacanthusHex** [comment] 2025-10-12 20:14
Recently, I did some further digging, and I found that if the first font doesn't contain the `U+0020 SPACE` character, Aves will render the first character after `U+2068 FIRST STRONG ISOLATE` as tofu block or just nothing. I think it should be a bug of Flutter, but I can't verify.
