### ISSUE TITLE
Album grouping.

### ISSUE THREAD

**Issue by DroidFloyd** [deckerst/aves#397] opened 2022-11-11 21:39 UTC
Would kindly love to have album grouping as or like Samsung Gallery. Reason being.
1.Organized access to multiple albums.
2.Reduces scrolling and confusion (if there are multiple albums, as in my case.)

Aves is currently the best third-party Gallery app out now imo. Wishing you the best for the future. Much appreciation for building and providing this app for us. Blessings

**Comment by deckerst** [comment] 2022-11-11 21:46
Welcome to GitHub!

I think your suggestion is a duplicate of this one:
- #268

You can upvote it by adding a thumb-up reaction 👍 to the top post. You can also subscribe to the issue to get updates (discussion, progress).

**Closed by deckerst** 2022-11-11 21:46 UTC
Labels: type:feature
