### ISSUE TITLE
Manual image geotagging

### ISSUE THREAD

**Issue by flexagoon** [deckerst/aves#153] opened 2022-01-07 09:49 UTC
**Is your feature request related to a problem? Please describe.**
Aside from my main camera app I also use a third-party one, which takes better quality pictures. Also in some cases I take a picture on someone else's phone and they send it to me. In both of those cases, the image will not have a geotag.

**Describe the solution you'd like**
I'd like a button in Aves to add geolocation to an image the same way that we can edit date and time metadata.

**Comment by deckerst** [comment] 2022-01-07 09:53
I believe this is a duplicate of #2, but feel free to reopen if I misunderstood.

**Closed by deckerst** 2022-01-07 09:53 UTC
Labels: close:duplicate, type:feature

**Comment by flexagoon** [comment] 2022-01-07 10:08
Oh, yes it is, sorry, didn't see that.
